### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by simovesterinen** [knizhnik/imcs#46]
Hi,

I have a question about disk mode and varchar dictionary.

If I use varchar string then imcs is using dictionary which is really great :)
but is dictionary always stored to shared memory or is it using disk for dictionary too? 
Example: If I have 32 GB of ram in my server machine and data in imcs is going to be over RAM allocated for shared buffers (24 GB) I should use disk mode. In this case should I allocate a lot of memory for dictionary or for imcs_cache?
My dictionary size is about 4 GB so should I put for example 18 GB for cache_size? What would be your recommendations? The total data size of data in imcs is going to be around 128 GB.

Another thing is about using using imcs in the same instance of postgresql in different databases.
If I use imcs in many databases inside one postgresql instance, should the names of tables be unique or can imcs handle same table names in different databases as separate data?

Thanks you again in advance :)

-Simo

**Comment by knizhnik** [comment]
Hi,

IMCS is using PostgreSQL hash table for implementing dictionary,
it means that hash table pages can not be swapped to the disk.
So complete dictionary has to fit in memory.
Moreover, I think that using such dictionary is sensible only if it is
in-memory, because lookup in disk-based hash table adds too much overhead.

Concerning second question:  IMCS currently completely replies on the given
tables names.
It knows nothing about databases and schemas. It is up to you how to
specify proper context.
May be in future I will add some support of namespaces but first of all I
need to understand myself how it should like.


2015-06-22 10:24 GMT+03:00 simovesterinen <notifications@github.com>:
